### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by lulianLiu** [cv-rits/MonoScene#31]
Dear author, you said that Use smaller 2D backbone by chaning the [basemodel_name and num_features](https://github.com/cv-rits/MonoScene/blob/master/monoscene/models/unet2d.py#L177)
The pretrained model name is [here](https://github.com/rwightman/gen-efficientnet-pytorch#ported-weights). You can try the efficientnet B5 can reduces the memory, I want to know the B5 weight  and the value of num_features?

**Comment by anhquancao** [comment]
You can try the "tf_efficientnet_b5_ns" and the num_features should be 2048 if I am correct.

**Comment by lulianLiu** [comment]
I have tried it ,but the error is:RuntimeError: Given groups=1, weight of size [1024, 2272, 3, 3], expected input[1, 2224, 30, 40] to have 2272 channels, but got 2224 channels instead

**Comment by lulianLiu** [comment]
> You can try the "tf_efficientnet_b5_ns" and the num_features should be 2048 if I am correct.

I have tried it ,but the error is:RuntimeError: Given groups=1, weight of size [1024, 2272, 3, 3], expected input[1, 2224, 30, 40] to have 2272 channels, but got 2224 channels instead

> You can try the "tf_efficientnet_b5_ns" and the num_features should be 2048 if I am correct.



> You need to adapt the skip_input= for all upsampling layer also. https://github.com/cv-rits/MonoScene/blob/master/monoscene/models/unet2d.py#L76 for example
> 
> ```
> self.up16 = UpSampleBN(
>                 skip_input=features + 224, output_features=self.feature_1_16
>             )
> ```
> 
> you need to change "+ 224" by another number to match the encoder feature dimension

how to make sure of the skip_input add?

**Comment by lulianLiu** [comment]
> From the error message, the input dim is 2224 so you need to change the **skip_input** value to **features + some number** to match 2224. So with features=2048 as when you use the b5, **some number** should be 2224 - 2048. You should do the same with other upsampling layer.

sorry, I have not  understannd. Have any approches to solve?

**Comment by anhquancao** [comment]
you can simply set skip_input=2224 as:
```
self.up16 = UpSampleBN(
    skip_input=2224, output_features=self.feature_1_16
)
```
and for others up8, up4, ... you can see the error message and change accordingly

**Comment by anhquancao** [comment]
Another simpler approach is to keep the b7 and set this **features** variable to a smaller number liks 
`
features=256
`
https://github.com/cv-rits/MonoScene/blob/master/monoscene/models/unet2d.py#L40

**Comment by lulianLiu** [comment]
> you can simply set skip_input=2224 as:
> 
> ```
> self.up16 = UpSampleBN(
>     skip_input=2224, output_features=self.feature_1_16
> )
> ```
> 
> and for others up8, up4, ... you can see the error message and change accordingly

I solve it. But also cuda out of memory. Have any approch to reduce ?

**Comment by lulianLiu** [comment]
> Another simpler approach is to keep the b7 and set this **features** variable to a smaller number liks `features=256` https://github.com/cv-rits/MonoScene/blob/master/monoscene/models/unet2d.py#L40

It also didn't work
RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 2; 14.62 GiB total capacity; 10.56 GiB already allocated; 9.00 MiB free; 10.74 GiB reserved in total by PyTorch)

**Comment by anhquancao** [comment]
The model use full 32g GPU so you need to reduce the memory more. You can also reduce the input image.

**Comment by lulianLiu** [comment]
> The model use full 32g GPU so you need to reduce the size of the network even more to fit into 14G. You can also reduce the input image size by half, becareful to scale the 3D-> 2D projection accordingly.

Thanks. I use B1 and reduce the image_size by half, now it works.

**Comment by anhquancao** [comment]
Great! I glad to hear that.
